#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: f4a13a5a93c1
#
Name     : grig
Version  : 0.9.0
Release  : 14
URL      : https://github.com/fillods/grig/releases/download/GRIG-0_9_0/grig-0.9.0.tar.gz
Source0  : https://github.com/fillods/grig/releases/download/GRIG-0_9_0/grig-0.9.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: grig-bin = %{version}-%{release}
Requires: grig-data = %{version}-%{release}
Requires: grig-license = %{version}-%{release}
Requires: grig-locales = %{version}-%{release}
Requires: grig-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : gettext
BuildRequires : hamlib-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gtk+-2.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: backport-connect-connectrig.patch
Patch2: backport-const-struct-rig_caps-struct-rig_caps.patch
Patch3: backport-Restore-rig_get-set_split-macros.patch

%description
# Grig
## About
**Grig** is a graphical user interface for the Ham Radio Control Libraries. It is
intended to be simple and generic, presenting the user with the same interface
regardless of which radio they use.

%package bin
Summary: bin components for the grig package.
Group: Binaries
Requires: grig-data = %{version}-%{release}
Requires: grig-license = %{version}-%{release}

%description bin
bin components for the grig package.


%package data
Summary: data components for the grig package.
Group: Data

%description data
data components for the grig package.


%package license
Summary: license components for the grig package.
Group: Default

%description license
license components for the grig package.


%package locales
Summary: locales components for the grig package.
Group: Default

%description locales
locales components for the grig package.


%package man
Summary: man components for the grig package.
Group: Default

%description man
man components for the grig package.


%prep
%setup -q -n grig-0.9.0
cd %{_builddir}/grig-0.9.0
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735945934
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1735945934
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/grig
cp %{_builddir}/grig-%{version}/COPYING %{buildroot}/usr/share/package-licenses/grig/b47456e2c1f38c40346ff00db976a2badf36b5e3 || :
export GOAMD64=v2
GOAMD64=v2
%make_install
%find_lang grig

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/grig

%files data
%defattr(-,root,root,-)
/usr/share/grig/AUTHORS
/usr/share/grig/COPYING
/usr/share/grig/ChangeLog
/usr/share/grig/NEWS
/usr/share/grig/README.md
/usr/share/pixmaps/grig/digits_normal.png
/usr/share/pixmaps/grig/digits_small.png
/usr/share/pixmaps/grig/grig-logo.png
/usr/share/pixmaps/grig/ic910.png
/usr/share/pixmaps/grig/smeter.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/grig/b47456e2c1f38c40346ff00db976a2badf36b5e3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/grig.1

%files locales -f grig.lang
%defattr(-,root,root,-)

