#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : grig
Version  : 0.8.1
Release  : 1
URL      : https://downloads.sourceforge.net/project/groundstation/Grig/0.8.1/grig-0.8.1.tar.gz
Source0  : https://downloads.sourceforge.net/project/groundstation/Grig/0.8.1/grig-0.8.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: grig-bin
Requires: grig-data
Requires: grig-locales
Requires: grig-doc
BuildRequires : gettext
BuildRequires : hamlib-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gtk+-2.0)

%description
1. About Grig
Grig is a graphical user interface for the Ham Radio Control Libraries. It is
intended to be simple and generic, presenting the user to the same interface
regardless of which radio he or she uses.

%package bin
Summary: bin components for the grig package.
Group: Binaries
Requires: grig-data

%description bin
bin components for the grig package.


%package data
Summary: data components for the grig package.
Group: Data

%description data
data components for the grig package.


%package doc
Summary: doc components for the grig package.
Group: Documentation

%description doc
doc components for the grig package.


%package locales
Summary: locales components for the grig package.
Group: Default

%description locales
locales components for the grig package.


%prep
%setup -q -n grig-0.8.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1508867251
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1508867251
rm -rf %{buildroot}
%make_install
%find_lang grig

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/grig

%files data
%defattr(-,root,root,-)
/usr/share/grig/AUTHORS
/usr/share/grig/COPYING
/usr/share/grig/ChangeLog
/usr/share/grig/NEWS
/usr/share/grig/README
/usr/share/pixmaps/grig/digits_normal.png
/usr/share/pixmaps/grig/digits_small.png
/usr/share/pixmaps/grig/grig-logo.png
/usr/share/pixmaps/grig/ic910.png
/usr/share/pixmaps/grig/smeter.png

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files locales -f grig.lang
%defattr(-,root,root,-)

